apiVersion: v1
kind: ServiceAccount
metadata:
  name: webkubectl
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: webkubectl-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webkubectl-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: webkubectl-role
subjects:
  - kind: ServiceAccount
    name: webkubectl
    namespace: default

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    k8s-app: webkubectl-agent
  name: webkubectl-agent
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: webkubectl-agent
  serviceName: webkubectl-agent
  template:
    metadata:
      labels:
        k8s-app: webkubectl-agent
    spec:
      containers:
        - env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          image: ccr.ccs.tencentyun.com/datamore/webkubectl-agent
          imagePullPolicy: Always
          name: webkubectl-agent
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    type: RollingUpdate
